export const previousLandUses = [
  { id: "none", label: "Undeveloped / No prior use" },
  { id: "residential", label: "Residential" },
  { id: "commercial", label: "Commercial" },
  { id: "mixed_use", label: "Mixed Use" },
  { id: "agriculture", label: "Agriculture" },
  { id: "industrial", label: "Industrial" },
  { id: "institutional", label: "Institutional (Schools, Hospitals, etc.)" },
  { id: "open_space", label: "Public Open Space / Park" },
  { id: "conservation", label: "Conservation / Protected Area" },
  { id: "vacant", label: "Vacant / Undeveloped Land" },
  { id: "extraction", label: "Extractive / Mining Site" },
  { id: "transport", label: "Transport / Warehousing" },
  { id: "utility", label: "Utility / Infrastructure" },
  { id: "religious", label: "Place of Worship" },
  { id: "emergency_services", label: "Emergency / Security Services" },
  { id: "recreational", label: "Recreational / Sports Facility" },
  { id: "tourism", label: "Tourism / Hospitality Facility" },
  { id: "redevelopment_zone", label: "Redevelopment / Slum Upgrade" },
  { id: "herbal", label: "Herbal Medicine Use" },
];
